### ISSUE TITLE
Improve plot design

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/OptimizedEinsum.jl#25]
Plots of `ContractionPath` would look more awesome if we could get rid of the grid and the axis lines (do not apply to our plots), and add a color bar.

@jofrevalles could you take a look at this? We might want to do the same later in `Tenet`.

**Comment by jofrevalles** [comment]
What do you think of something like this?

```julia
julia> using OptimizedEinsum
julia> using CairoMakie
julia> output, inputs, size_dict = rand_equation(15, 5)
julia> path = contractpath(Greedy, inputs, output, size_dict)
julia> plot(path; colormap=:viridis)
```
![image](https://user-images.githubusercontent.com/61060572/215760927-7054171c-79a3-4258-ada4-c500cce4c9ee.png)

**Comment by mofeing** [comment]
I like it!

can something be done for the node size? Like the color bar but for from min node size to max node size
